# Master Configuration.

[module]
name = "master"
role = "master"
version = "v1"
# web request request signature key
signkey = ""
data-path = "/tmp/baudengine/master1/data"

[log]
log-path = "/tmp/baudengine/master1/log"
#debug, info, warn, error
level="debug"
#debug, info, warn
raft-level="info"

[cluster]
cluster-id = "1"
node-id = 1
raft-heartbeat-interval=500
raft-retain-logs-count=100

[[cluster.nodes]]
node-id=1
host="127.0.0.1"
http-port=8817
rpc-port=18817
raft-heartbeat-port=8816
raft-replicate-port=8815

[[cluster.nodes]]
node-id=2
host="127.0.0.1"
http-port=8827
rpc-port=18827
raft-heartbeat-port=8826
raft-replicate-port=8825

[[cluster.nodes]]
node-id=3
host="127.0.0.1"
http-port=8837
rpc-port=18837
raft-heartbeat-port=8836
raft-replicate-port=8835

[ps]
rpc-port=58000
admin-port=58001
heartbeat-interval=5000
raft-heartbeat-interval=100
raft-heartbeat-port=58002
raft-replicate-port=58003
raft-retain-logs=10000
raft-replica-concurrency=1
raft-snapshot-concurrency=1

